# Generated by Django 5.1.6 on 2026-02-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0002_alter_actualite_id_alter_evenement_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Créé'), ('UPDATE', 'Modifié'), ('DELETE', 'Supprimé'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion')], max_length=20)),
                ('modele', models.CharField(max_length=100)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], default='INFO', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('RESPONSABLE', 'Responsable'), ('TRESORIER', 'Trésorier'), ('SECRETAIRE', 'Secrétaire'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=20)),
                ('peut_creer_rapport', models.BooleanField(default=True)),
                ('peut_gerer_membres', models.BooleanField(default=False)),
                ('peut_gerer_finances', models.BooleanField(default=False)),
                ('peut_gerer_formations', models.BooleanField(default=False)),
                ('peut_publier_actualites', models.BooleanField(default=False)),
                ('peut_gerer_commissions', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='GestionDepartement.membre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
