# Generated by Django 5.1.6 on 2026-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0003_activitelog_notification_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='departement',
            field=models.CharField(blank=True, choices=[('ADA', 'ADA'), ('ADN', 'ADN'), ('CLASSE_BATEME', 'Classe de Batême'), ('COMMUNICATION', 'Communication'), ('ECODIM', 'ECODIM'), ('EVANGELISATION', 'Evangelisation'), ('GESTION_CULTE', 'Gestion de Culte'), ('LOGISTIQUE', 'Logistique'), ('MUSIQUE_LOUANGE', 'Musique et Louange'), ('PORTIER', 'Portier'), ('SAINTE_CENE', 'Sainte Cène')], help_text='Département auquel le membre appartient', max_length=30),
        ),
        migrations.AddField(
            model_name='membre',
            name='est_responsable',
            field=models.BooleanField(default=False, help_text="Cocher si ce membre est responsable d'un département"),
        ),
    ]
