# Generated by Django 5.1.6 on 2026-02-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0005_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportculte',
            name='nom_departement',
            field=models.CharField(blank=True, help_text='Nom du département/Commission', max_length=50),
        ),
    ]
