# Generated by Django 5.1.6 on 2026-03-01 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0006_add_nom_departement_to_rapport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('ADA', 'ADA'), ('ADN', 'ADN'), ('CLASSE_BATEME', 'Classe de Batême'), ('COMMUNICATION', 'Communication'), ('ECODIM', 'ECODIM'), ('EVANGELISATION', 'Evangelisation'), ('GESTION_CULTE', 'Gestion de Culte'), ('LOGISTIQUE', 'Logistique'), ('MUSIQUE_LOUANGE', 'Musique et Louange'), ('PORTIER', 'Portier'), ('SAINTE_CENE', 'Sainte Cène')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_dirige', to='GestionDepartement.membre')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
    ]
