# Generated by Django 5.1.6 on 2026-03-02 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0007_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text='Année du budget')),
                ('mois', models.IntegerField(blank=True, help_text='Mois du budget (optionnel pour budget mensuel)', null=True)),
                ('categorie', models.CharField(choices=[('LOGISTIQUE', 'Logistique'), ('EQUIPEMENT', 'Équipement'), ('FORMATION', 'Formation'), ('COMMUNICATION', 'Communication'), ('SOCIAL', 'Action sociale'), ('CULTUREL', 'Activité culturelle'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant_prevu', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_realise', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('EN_COURS', 'En cours'), ('TERMINER', 'Terminé'), ('ANNULE', 'Annulé')], default='PREVU', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-annee', '-mois', 'categorie'],
                'unique_together': {('annee', 'mois', 'categorie')},
            },
        ),
        migrations.CreateModel(
            name='Impayes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cotisation', models.CharField(default='COTISATION', help_text='Type de cotisation', max_length=50)),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('periode_debut', models.DateField(help_text='Période de début (ex: mois/année)')),
                ('periode_fin', models.DateField(blank=True, help_text='Période de fin', null=True)),
                ('date_echeance', models.DateField(help_text="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, help_text='Date du paiement', null=True)),
                ('statut', models.CharField(choices=[('EN_RETARD', 'En retard'), ('RELANCE', 'Relancé'), ('PAIE_PARTIEL', 'Payé partiellement'), ('SOLDE', 'Soldé'), ('ANNULE', 'Annulé')], default='EN_RETARD', max_length=20)),
                ('nb_relances', models.IntegerField(default=0)),
                ('date_derniere_relance', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impayes', to='GestionDepartement.membre')),
            ],
            options={
                'verbose_name': 'Impayé',
                'verbose_name_plural': 'Impayés',
                'ordering': ['-periode_debut', '-date_echeance'],
            },
        ),
    ]
