# Generated by Django 5.1.6 on 2026-03-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0008_budget_impayes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_media', models.CharField(choices=[('image', 'Photo'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('fichier', models.FileField(help_text='Photo ou vidéo', upload_to='galerie/')),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDepartement.membre')),
            ],
            options={
                'verbose_name': 'Média galerie',
                'verbose_name_plural': 'Médias galerie',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
