# Generated by Django 5.1.6 on 2026-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0009_mediagalerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='departement',
            field=models.CharField(blank=True, help_text='Département qui a créé la formation', max_length=50),
        ),
        migrations.AddField(
            model_name='formation',
            name='statut_validation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
