# Generated by Django 5.1.6 on 2026-03-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0010_formation_departement_formation_statut_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='groupe_sentinelle',
            field=models.CharField(blank=True, default='', help_text='Groupe de sentinelle (A, B, C...)', max_length=50),
        ),
    ]
