# Generated by Django 5.1.6 on 2026-03-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0011_alter_membre_groupe_sentinelle'),
    ]

    operations = [
    ]
