# Generated by Django 5.1.6 on 2026-03-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0012_add_departement_to_groupeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeservice',
            name='departement',
            field=models.CharField(blank=True, help_text='Département propriétaire du groupe', max_length=30),
        ),
    ]
