# Generated by Django 5.1.6 on 2026-03-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0013_groupeservice_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, help_text='Image/Affiche', null=True, upload_to='formations/images/'),
        ),
        migrations.AddField(
            model_name='formation',
            name='video',
            field=models.FileField(blank=True, help_text='Vidéo de formation', null=True, upload_to='formations/videos/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='departement',
            field=models.CharField(blank=True, help_text='Département destinataire (vide = tous)', max_length=50),
        ),
        migrations.AlterField(
            model_name='formation',
            name='supports',
            field=models.FileField(blank=True, help_text='Document PDF', null=True, upload_to='supports_formation/'),
        ),
    ]
