# Generated by Django 5.1.6 on 2026-03-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDepartement', '0014_formation_image_formation_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='departement',
            field=models.CharField(blank=True, help_text='Département concerné par la transaction', max_length=30),
        ),
    ]
